[package]
name = "logging-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.0"
tokio = { version="1", features = ["full"] }
tonic = "0.11.0"
tracing = "0.1.40"
tracing-subscriber = { version="0.3", features = ["env-filter", "json"] }

[build-dependencies]
tonic-build = "0.11"
